language: python
# install dependencies
install:
  - pip3 install -r requirements.txt
# run tests
script:
  - mkdir src/config
  - touch src/config/config.json
  - pytest src/test -vv --cov
notifications:
  email:
    recipients:
      - mmariotti@fi.uba.ar
    on_success: change
    on_failure: always
