language: python
# install dependencies
install:
  - pip3 install -r requirements.txt
# run tests
script:
  - pytest src/test -vv
notifications:
  email:
    recipients:
      - mmariotti@fi.uba.ar
    on_success: change
<<<<<<< HEAD
    on_failure: always
=======
    on_failure: always
>>>>>>> 43e4c89 (Change email notifiactions settings)
